# Generated by Django 3.2.8 on 2021-11-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hl_apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
