# Generated by Django 3.2.8 on 2021-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tag',
            field=models.CharField(default='whiteTag', max_length=20),
        ),
    ]
