# Generated by Django 3.2.10 on 2022-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
