# Generated by Django 3.2.10 on 2022-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quoteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_tags',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
