# Generated by Django 3.2.10 on 2022-01-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quotetags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteconfiguration',
            name='quote_order',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='quotetags',
            name='quote_tags',
            field=models.CharField(blank=True, default='', max_length=20000, null=True),
        ),
    ]
